logo: banner-transparent.png
title: "Fasten Health Documentation"
remote_theme: just-the-docs/just-the-docs
search_enabled: true
aux_links:
  "fastenhealth.com":
    - "https://www.fastenhealth.com"
heading_anchors: true
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
back_to_top: true
back_to_top_text: "Back to top"
footer_content: 'Copyright &copy; 2022 Fasten Health'
gh_edit_link: true
gh_edit_link_text: "Suggestions? Edit this page on GitHub."
gh_edit_repository: "https://github.com/fastenhealth/docs"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
color_scheme: light
callouts:
  error:
    title: Error
    color: red
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: blue
ga_tracking: G-WZK565L4EN
mermaid:
  version: "9.1.3"
# TOC Settings
#toc:
#  min_level: 1
#  max_level: 3
#  list_id: toc
#  list_class: section-nav
#  sublist_class: ''
#  item_class: toc-entry
#  item_prefix: toc-
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-toc
